export const SCHOOL_TYPE_OPTIONS = [
  { value: '__group_de', label: 'Deutschland', disabled: true },
  { value: 'grundschule', label: 'Grundschule' },
  { value: 'hauptschule', label: 'Hauptschule' },
  { value: 'realschule_de', label: 'Realschule' },
  { value: 'gymnasium_de', label: 'Gymnasium' },
  { value: 'gesamtschule', label: 'Gesamtschule' },
  { value: 'sekundarschule_gemeinschaftsschule', label: 'Sekundarschule / Gemeinschaftsschule' },
  { value: 'foerderschule', label: 'Förderschule' },

  { value: '__group_at', label: 'Österreich', disabled: true },
  { value: 'volksschule', label: 'Volksschule' },
  { value: 'mittelschule', label: 'Mittelschule' },
  { value: 'ahs_unterstufe', label: 'AHS (Unterstufe)' },
  { value: 'ahs_oberstufe', label: 'AHS (Oberstufe)' },
  { value: 'bhs', label: 'Berufsbildende höhere Schule (BHS)' },
  { value: 'bms', label: 'Berufsbildende mittlere Schule (BMS)' },
  { value: 'polytechnische_schule', label: 'Polytechnische Schule' },
  { value: 'sonderschule_inklusion_at', label: 'Sonderschule / inklusiver Unterricht' },

  { value: '__group_ch', label: 'Schweiz', disabled: true },
  { value: 'primarschule', label: 'Primarschule' },
  { value: 'sekundarschule_ch', label: 'Sekundarschule' },
  { value: 'realschule_ch', label: 'Realschule' },
  { value: 'bezirksschule', label: 'Bezirksschule' },
  { value: 'gymnasium_kantonsschule', label: 'Gymnasium / Kantonsschule' },
  { value: 'fms', label: 'Fachmittelschule (FMS)' },
  { value: 'bms_ch', label: 'Berufsmaturitätsschule (BMS)' },
  { value: 'sonderschule_inklusion_ch', label: 'Sonderschule / inklusiver Unterricht' },

  { value: '__group_org', label: 'Organisationen & Sonstige', disabled: true },
  { value: 'verein', label: 'Verein' },
  { value: 'unternehmen', label: 'Unternehmen' },
  { value: 'privat', label: 'Privat' },
  { value: 'andere', label: 'Andere / Other' },
]
